--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ImmoDevs/FlySpeed-PM5
build-by-default: true
branches:
- main
projects:
  FlySpeed-PM5:
    path: ""
    icon: "icon.png"
    lint:
      phpstan: false
...
