---
name: FlySpeed
version: 0.0.1
main: WolfDen133\FlySpeed\Main
api: 4.12.0
src-namespace-prefix: WolfDen133\FlySpeed

permissions:
  flyspeed.command.use:
    description: Allows the use of the flyspeed command
    default: op
...
