---
name: FlySpeed
main: WolfDen133\FlySpeed\Main
version: 0.0.2
api: 5.0.0
authors: [WolfDen133, ImmoDevs]
src-namespace-prefix: WolfDen133\FlySpeed

permissions:
  flyspeed.command.use:
    description: Allows the use of the flyspeed command
    default: op
...
